import logging
import os
import pickle
from tqdm import tqdm
import argparse
import re
import json

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from factscore.factscorer import FactScorer


# Configure logging at the beginning of your script
logging.basicConfig(
    level=logging.INFO, 
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler("generation.log"),
        logging.StreamHandler()
    ]
)

# Consolidated exclusion patterns using regex alternation and common keywords
exclusion_patterns = re.compile(
    r'\b(?:I\s+(?:cannot|was unable to|do not|have no)\s+(?:find|provide|locate|access)|'
    r'(?:No|Insufficient|Cannot|Unable)\s+(?:information|data|details|records|bio|profile|content)|'
    r'(?:I\s+am\s+not\s+sure|Note\s+(?:that|,))|'
    r'(?:No\s+(?:additional|further|relevant)\s+information))\b',
    flags=re.IGNORECASE
)

def load_entities(entities_file, entity_range=None, max_entities=None):
    """
    Load prompt entities from a file, optionally selecting a range and limiting the number.

    Args:
        entities_file (str): Path to the file containing entities.
        entity_range (str, optional): Slice string in the format 'start:end'.
        max_entities (int, optional): Maximum number of entities to load after applying the range.

    Returns:
        list: A list of selected entities.
    """
    with open(entities_file, 'r') as f:
        ents = f.read().splitlines()

    # Apply range slicing if specified
    if entity_range:
        start, end = None, None
        parts = entity_range.split(':')
        if len(parts) == 2:
            start = int(parts[0]) if parts[0] else None
            end = int(parts[1]) if parts[1] else None
        elif len(parts) == 1:
            start = int(parts[0])
        ents = ents[start:end]
        logging.info(f'Applied entity range "{entity_range}": {len(ents)} entities selected.')

    # Apply max_entities limit if specified
    if max_entities:
        ents = ents[:max_entities]
        logging.info(f'Applied max_entities={max_entities}: {len(ents)} entities selected.')

    logging.info(f'Total entities loaded: {len(ents)}.')
    return ents

def initialize_model(hf_model_name, device='cuda', max_memory='80GIB'):
    """Initialize the tokenizer and model."""
    path = hf_model_name
    tokenizer = AutoTokenizer.from_pretrained(path)
    model = AutoModelForCausalLM.from_pretrained(
        path, 
        device_map="auto", 
        torch_dtype=torch.float16,
        cache_dir=os.environ["HF_DATASETS_CACHE"],
    )
    logging.info(f'Model "{hf_model_name}" loaded on device "{device}".')
    return tokenizer, model

def post_process_bio(generated_text: str, prompt: str) -> str:
    """
    Post-process the generated bio to ensure completeness and remove extraneous content.
    
    Args:
        generated_text (str): The raw text generated by the model.
        prompt (str): The prompt that was sent to the model.
    
    Returns:
        str: The cleaned and validated bio.
    """
    # Remove the prompt from the generated text
    bio = generated_text.replace(prompt, "").strip()
    # Ensure the bio ends with a period. If not, truncate to the last complete sentence.
    if not bio.endswith('.'):
        last_period = bio.rfind('.')
        if last_period != -1:
            bio = bio[:last_period + 1]
    
    # Remove any text after the first bio if multiple bios are generated
    bio = re.split(r'\n?Tell me a bio of', bio, flags=re.IGNORECASE)[0].strip()
    
    # Remove explanations about inability to find more information using the consolidated pattern
    bio = exclusion_patterns.split(bio)[0].strip()
    
    return bio

def generate_responses(ents, tokenizer, model, make_prompt, max_new_tokens, temperature, verbose=False):
    """Generate responses for each entity."""
    generations = []
    for ent in tqdm(ents, desc='Generating responses'):
        prompt = make_prompt(ent)
        inputs = tokenizer([prompt], return_tensors="pt").to('cuda')
        outputs = model.generate(
            **inputs, 
            max_new_tokens=max_new_tokens, 
            do_sample=True, 
            temperature=temperature,
            eos_token_id=tokenizer.eos_token_id  # Ensure proper end of generation
        )
        generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
        
        # Apply post-processing to the generated text
        bio = post_process_bio(generated_text, prompt)
        generations.append(bio)

        if verbose:
            logging.info("\n" + "="*50)
            logging.info(f"Entity: {ent}")
            logging.info(f"Generated Response: {bio}")
            logging.info("="*50 + "\n")
    
    return generations

def compute_factscore(ents, generations, openai_key, gamma=10):
    """Compute FactScore for the generated responses."""
    fs = FactScorer(cache_dir='./FActScore/.cache')
    return fs.get_score(ents, generations, gamma=gamma, verbose=True)

def save_output(factscore_output, model_name, entity_range, temperature, max_new_tokens, api, output_dir, backup_dir, use_clamped):
    """Save the FactScore output to files."""
    os.makedirs(output_dir, exist_ok=True)
    
    filename = f"{model_name}{'_clamped' if use_clamped else ''}_fact_scores_ent_{entity_range}_temp_{temperature}_maxtok_{max_new_tokens}_api_{api}.pkl"
    for dir_path in [output_dir]:
        with open(os.path.join(dir_path, filename), 'wb') as f:
            pickle.dump(factscore_output, f)
    logging.info(f'FactScore output saved to "{output_dir}".')

def get_postamble():
    """Return a string containing postamble for prompting."""
    postamble = """
Provide as many specific details and examples as possible (such as names of \
people, numbers, events, locations, dates, times, etc.). 
"""
    return postamble.strip()

def go_make_prompt(entity, postamble):
    """Construct a few-shot prompt with the given entity."""
    return f"Who is {entity}? {postamble}"

def main():
    parser = argparse.ArgumentParser(description='FactScore Generation and Evaluation')
    parser.add_argument('--hf_model_name', type=str, default='meta-llama/Llama-3.1-70B-Instruct', help='Hugging Face model name, e.g. google/gemma-2-9b-it')
    parser.add_argument('--model_name', type=str, default='Llama3.1-70B', help='Model name identifier, e.g. Gemma2-9B')
    parser.add_argument('--entities_file', type=str, default='./FActScore/data/prompt_entities.txt', help='File containing entities')
    parser.add_argument('--max_new_tokens', type=int, default=512, help='Max number of new tokens to generate')  # Set to 128
    parser.add_argument('--temperature', type=float, default=0.01, help='Sampling temperature')
    parser.add_argument('--api', type=str, default='gpt-4o-mini', help='API used for FactScore. Not used.')
    parser.add_argument('--openai_key', type=str, help='OpenAI API key for FactScorer')
    parser.add_argument('--gamma', type=int, default=10, help='Gamma parameter for FactScorer')
    parser.add_argument('--device', type=str, default='cuda', help='Computation device')
    parser.add_argument('--max_memory', type=str, default='80GIB', help='Max memory per device for model')
    parser.add_argument('--output_dir', type=str, default='./FActScore/data', help='Directory to save outputs')
    parser.add_argument('--use_clamped', type=bool, default=False, help='Help distinguish file names when clamping')
    parser.add_argument('--entity_range', type=str, default=None, help='Range of entities to process, e.g., "100:", "100:200", ":200"')
    parser.add_argument('--max_entities', type=int, default=30, help='Maximum number of entities to process after applying the range')
    parser.add_argument('--verbose', action='store_true', help='Enable verbose output for generated responses')

    args = parser.parse_args()
    
    ents = load_entities(args.entities_file, entity_range=args.entity_range, max_entities=args.max_entities)
    # tokenizer, model = initialize_model(args.hf_model_name, device=args.device, max_memory=args.max_memory)
    
    # postamble = get_postamble()
    # make_prompt = lambda x: go_make_prompt(x, postamble)
    
    # generations = generate_responses(
    #     ents, 
    #     tokenizer, 
    #     model, 
    #     make_prompt, 
    #     args.max_new_tokens, 
    #     args.temperature,
    #     verbose=args.verbose
    # )
    
    with open('./results_all/llama3_70b_25_30_wikibio_gen_results.json', 'r') as f:
        gens = json.load(f)
        
    generations = [gen['response'] for gen in gens]
    
    factscore_output = compute_factscore(ents, generations, args.openai_key, gamma=args.gamma)
    
    save_output(
        factscore_output, 
        args.model_name, 
        args.entity_range,
        args.temperature, 
        args.max_new_tokens, 
        args.api, 
        args.output_dir, 
        None,
        args.use_clamped,
    )
    
    print('FactScore output saved successfully.')

if __name__ == '__main__':
    main()
