MAJOR = 'Major False'

MINOR =  'Minor False'

data = [
    [
        0,
        '''Who is Suthida? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Suthida Bajrasudhabimalalakshana is the queen consort of Thailand.',
            'Suthida Bajrasudhabimalalakshana was born on June 3, 1978.',
            'Suthida Bajrasudhabimalalakshana was born in Thailand.',
            'Suthida Bajrasudhabimalalakshana\'s mother is a homemaker.',
            'Suthida Bajrasudhabimalalakshana worked for Thai Airways International from 2003 to 2014.',
            'Suthida was appointed as the queen consort.',
            'Suthida was appointed as the queen consort on May 1, 2019.',
            'King Bhumibol Adulyadej has died.',
            'The marriage of Suthida Bajrasudhabimalalakshana and King Maha Vajiralongkorn took place on May 1, 2019.',
            'The wedding ceremony of Suthida Bajrasudhabimalalakshana and King Maha Vajiralongkorn took place in Bangkok.',
            'The wedding ceremony of Suthida Bajrasudhabimalalakshana and King Maha Vajiralongkorn was attended by government officials.',
            'Suthida has supported the Princess Mother Memorial Hospital.',
            'The Princess Mother Memorial Hospital is an organization.',
            'Suthida Bajrasudhabimalalakshana is known for her simplicity.',
            'Suthida Bajrasudhabimalalakshana is known for her modesty.',
            'The lifestyle of some members of the Thai royal family is described as extravagant.',
            'Suthida has been seen accompanying King Vajiralongkorn.',
            'Suthida has accompanied King Vajiralongkorn on various events.',
            'Suthida Bajrasudhabimalalakshana has been described due to her willingness to engage with ordinary people.',
            'Suthida Bajrasudhabimalalakshana has been involved in supporting the development of rural areas.',
        ],
        [
            True,
            True,
            True,
            MAJOR,
            MAJOR,
            True,
            True,
            True,
            True,
            True,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            True,
            True,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        1,
        '''Who is Miguel Ángel Félix Gallardo? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Miguel Ángel Félix Gallardo is also known as El Padrino (The Godfather).',
            'Félix Gallardo was born in Mexico.',
            'Félix Gallardo began his criminal career as a police officer.',
            'Miguel Ángel Félix Gallardo began his criminal career in the 1960s.',
            'The Guadalajara Cartel smuggled large quantities of cocaine and marijuana into the United States.',
            'Félix Gallardo was known for Félix Gallardo\'s lavish lifestyle.',
            'Félix Gallardo was arrested.',
            'Miguel Ángel Félix Gallardo was convicted of conspiracy to distribute cocaine.',
            'Miguel Ángel Félix Gallardo\'s story has been the subject of several books.',
            'The 2018 Netflix series "Narcos: Mexico" is one of the films that features Miguel Ángel Félix Gallardo\'s story.',
            'Miguel Ángel Félix Gallardo is regarded as one of the most significant figures.',
        ],
        [
            True,
            True,
            True,
            MAJOR,
            True,
            MAJOR,
            True,
            MAJOR,
            True,
            True,
            True,
        ]
    ],
    [
        2,
        '''Who is Iggy Azalea? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Iggy Azalea is Australian.',
            'Iggy Azalea moved to the United States.',
            '"Fancy" is a hit single.',
            'The New Classic was certified platinum in the United States.',
            'Iggy Azalea was featured on the cover of Rolling Stone magazine in 2014.',
            'T.I. is a notable artist.',
            'Iggy Azalea was taking a hiatus to focus on her personal life.',
            'Iggy Azalea has struggled with anxiety.',
            'The title of Iggy Azalea\'s fourth studio album is "The End of an Era."',
            '"The End of an Era" included the single "Savior."',
            'The album "The End of an Era" debuted at number one on the US Billboard 200 chart.',
            'Iggy Azalea has been praised for her energetic live performances.',
        ],
        [
            True,
            True,
            True,
            True,
            MAJOR,
            True,
            True,
            MAJOR,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        3,
        '''Who is Fernando da Costa Novaes? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Fernando da Costa Novaes plays as a defender.',
            'Fernando da Costa Novaes has represented the Brazil national team at the under-23 level.',
            'Fernando da Costa Novaes helped Santos FC win the Copa Libertadores in 2011.',
            'Fernando da Costa Novaes helped Santos FC win the Copa Sudamericana in 2012.',
            'Fernando da Costa Novaes has national team success.',
            'Fernando da Costa Novaes was born in Santos, São Paulo, Brazil.',
            'Fernando da Costa Novaes has played for the Brazil national team at the under-23 level.',
            'Fernando da Costa Novaes won the Copa Libertadores in 2011.',
            'Fernando da Costa Novaes supports local community development projects.',
        ],
        [
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        4,
        '''Who is Jan Zamoyski? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Jan Zamoyski played a key role in the politics of Poland.',
            'Jan Zamoyski played a key role in the politics of Poland during the 17th century.',
            'Jan Zamoyski was a key figure in the development of the Polish-Lithuanian Commonwealth.',
            'Jan Zamoyski was a member of the Polish Sejm.',
            'Jan Zamoyski was a key figure in the negotiations with the Ottoman Empire.',
            'Zamoyski is considered one of the most important figures in Polish history.',
            'Jan Zamoyski\'s contributions to Polish history are celebrated today.',
            'The diverse population of the Polish-Lithuanian Commonwealth included Ukrainians.',
        ],
        [
            True,
            MAJOR,
            True,
            True,
            MAJOR,
            True,
            True,
            True,
        ]
    ],
    [
        5,
        '''Who is Radhika Apte? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Radhika Apte plays the role of Gaura in "Parched."',
            'Gaura is a character in "Parched."',
            'Radhika Apte has received several awards.',
            'Radhika Apte has been named as one of the most influential people in the world.',
            'Radhika Apte has been open about her personal life.',
            'Radhika Apte has a strong social media presence.',
            'Radhika Apte has a net worth of over $10 million.',
        ],
        [
            True,
            True,
            True,
            MAJOR,
            True,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        6,
        '''Who is David Galloway (writer)? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'David Galloway is a British writer and journalist.',
            'One of the books David Galloway has written is titled "The Complete Book of the Sea."',
            'David Galloway has been nominated for an Emmy Award.',
            'One of the topics David Galloway has written about is the impact of climate change on the ocean.',
            'One of the topics David Galloway has written about is the effects of pollution on marine life.',
            'David Galloway has written about the importance of protecting marine ecosystems.',
            'The Marine Conservation Institute is an organization that promotes conservation efforts.',
            'David Galloway has been based in the UK.',
            'Sir David Attenborough has been a mentor to David Galloway.',
            'David Galloway has written about the importance of protecting marine habitats.',
            'David Galloway has written about kelp forests.',
        ],
        [
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        7,
        '''Who is Cheyenne Brando? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Cheyenne Brando is the daughter of Marlon Brando.',
            'Cheyenne Brando was born on August 19th.',
            'Marlon Brando was a renowned actor.',
            'Marlon Brando had iconic roles in "The Godfather."',
            'Cheyenne Brando spent most of her childhood in Los Angeles.',
            'Cheyenne Brando spent most of her childhood in California.',
            'Marlon Brando died in 2004.',
            'Marlon Brando died at the age of 80.',
            'Cheyenne Brando has been involved in various scandals.',
            'The 2011 incident where Cheyenne Brando was arrested for allegedly assaulting a woman in a bar occurred in a bar.',
            'Cheyenne was arrested in 2014.',
            'Cheyenne Brando has been open about her struggles with addiction and mental health issues.',
            'Cheyenne Brando has worked as a model.',
            'Cheyenne Brando has worked with organizations that support mental health awareness.',
            'Cheyenne Brando continues to work as an entrepreneur.',
            'Cheyenne Brando has been open about her struggles.',
            'Cheyenne Brando has used her platform to raise awareness.',
        ],
        [
            True,
            MAJOR,
            True,
            True,
            MAJOR,
            MAJOR,
            True,
            True,
            True,
            MAJOR,
            MAJOR,
            True,
            True,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
        ]
    ],
    [
        8,
        '''Who is Mihai Eminescu? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Mihai Eminescu is considered one of the most important figures in Romanian literature.',
            'Moldavia is now part of Romania.',
            'Gheorghe Eminovici was a nobleman.',
            'Mihai Eminescu\'s mother was Smaranda Brăiloiu.',
            'Mihai Eminescu moved to Iași in 1866.',
            'Mihai Eminescu befriended other notable writers, such as Ioan Slavici and Titu Maiorescu.',
            'Titu Maiorescu is a notable writer.',
            'Mihai Eminescu befriended Titu Maiorescu.',
            'Mihai Eminescu continued to write poetry.',
            'Mihai Eminescu continued to write essays.',
            'Some of Mihai Eminescu\'s most famous works include the poem "Luceafărul."',
            'Some of Mihai Eminescu\'s most famous works include the novel "Nunta în Țara" (The Wedding in the Country).',
            '"Nunta în Țara" (The Wedding in the Country) is a novel by Mihai Eminescu.',
            'Some of Mihai Eminescu\'s most famous works include the collection of poems "Făt-Frumos din Țara Fainelor" (The Handsome Prince from the Land of Beauty).',
            'Mihai Eminescu was a prolific journalist.',
            'Mihai Eminescu contributed to several magazines.',
        ],
        [
            True,
            True,
            True,
            True,
            MAJOR,
            True,
            True,
            True,
            True,
            MAJOR,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            True,
        ]
    ],
    [
        9,
        '''Who is John Atkinson Grimshaw? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'John Atkinson Grimshaw died in 1893.',
            'John Atkinson Grimshaw worked for a firm.',
            'John Atkinson Grimshaw focused on landscapes.',
            'John Atkinson Grimshaw focused on nocturnal scenes.',
            'Grimshaw\'s paintings often depicted the Yorkshire countryside.',
            'John Atkinson Grimshaw captured the rivers in a range of light conditions.',
            'John Atkinson Grimshaw was known for John Atkinson Grimshaw\'s attention to detail.',
            'John Atkinson Grimshaw\'s paintings are held in high esteem.',
            'John Atkinson Grimshaw is considered an important British painter.',
            'John Atkinson Grimshaw is considered one of the most important British painters of the 19th century.',
            'John Atkinson Grimshaw died on October 13, 1893.',
            'John Atkinson Grimshaw was 57 years old at the time of his death.',
            'John Atkinson Grimshaw\'s legacy is celebrated through exhibitions.',
            'Publications feature John Atkinson Grimshaw\'s work.',
            'John Atkinson Grimshaw\'s life and work are the subject of ongoing research.',
        ],
        [
            True,
            True,
            MAJOR,
            True,
            MAJOR,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
        ]
    ],
    [
        10,
        '''Who is Maja Jager? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Maja Jager has won multiple World Championship titles in the women\'s 50m rifle 3 positions event.',
            'Maja Jager is a renowned sport shooter.',
            'Maja Jager finished 4th in the women\'s 50m rifle 3 positions event.',
            'Maja Jager won a gold medal in the women\'s 50m rifle 3 positions event at the European Championships in 2015.',
            'Maja Jager has won gold medals in the World Championships.',
            'Maja Jager has competed in several international competitions.',
            'Maja Jager finished 4th in the Olympic Games in 2016.',
            'Maja Jager regularly posts photos about her training.',
        ],
        [
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            True,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        11,
        '''Who is Richie Dorman? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Richie Dorman played as a return specialist.',
            'Richie Dorman played for the Seahawks.',
            'Richie Dorman played for the Packers.',
            'Richie Dorman caught 34 passes during Richie Dorman\'s time with the Packers.',
            'Richie Dorman retired from football due to a knee injury.',
            'Richie Dorman worked as a color commentator.',
            'Richie Dorman has worked for ESPN.',
            'Richie Dorman has been involved in various charitable endeavors.',
        ],
        [
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        12,
        '''Who is Braulio Lara? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Braulio Lara has been assigned to several teams.',
            'Braulio Lara has been assigned to the Corpus Christi Hooks.',
            'Tigres de Aragua is a team in the Venezuelan Winter League.',
            'A level of minor league baseball is the Midwest League.',
            'Braulio Lara has played in the Arizona Fall League.',
            'Braulio Lara had a 3.38 ERA in 2013.',
            'The assignment of Braulio Lara to the Binghamton Mets occurred in 2014.',
            'Braulio Lara has a fastball and curveball combination.',
        ],
        [
            True,
            MAJOR,
            True,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        13,
        '''Who is Katherine Ryan? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Katherine Ryan\'s comedy style often focuses on Katherine Ryan\'s relationships.',
            'Katherine Ryan has been open about her experiences as a single mother.',
            'Katherine Ryan has been open about her struggles with marriage.',
            'The Netflix special called "Glitter Room" is called "Glitter Room."',
            'Katherine Ryan has been praised for her humor.',
            'Katherine Ryan has been named as one of the most influential people in the world.',
            'Time magazine named Katherine Ryan as one of the most influential people in the world.',
            'Katherine Ryan has been a vocal supporter of the #MeToo movement.',
            'Katherine Ryan raises awareness about issues affecting women.',
            'Katherine Ryan\'s first marriage was to a man named Bobby Kootstra.',
            'Katherine Ryan has a daughter named Violet with her ex-husband Bobby Kootstra.',
            'Katherine Ryan has been a vocal supporter of several charities.',
            'Katherine Ryan was involved in a charity gala in 2019.',
        ],
        [
            True,
            True,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
            MAJOR,
            True,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        14,
        '''Who is Matthew Perry? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            '"Friends" is a popular American television sitcom.',
            'Chandler Bing is a character on "Friends."',
            'Witty one-liners were a hallmark of the character Chandler Bing played by Matthew Perry in "Friends."',
            'Matthew Perry has worked as a producer.',
            'St. Jude Children\'s Research Hospital is a charitable organization.',
            'Matthew Perry has spoken publicly about Matthew Perry\'s experiences with sobriety.',
            'Matthew Perry attributed the gastrointestinal perforation to years of heavy drinking.',
            'Matthew Perry has spoken publicly about his experiences with sobriety.',
            'The estimation of Matthew Perry\'s net worth is according to Celebrity Net Worth.',
        ],
        [
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            MAJOR,
        ]
    ],
    [
        15,
        '''Who is Amr Shabana? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Amr Shabana won the US Open in 2007.',
            'Amr Shabana won the Canary Wharf Classic in 2006.',
            'Amr Shabana won the Canary Wharf Classic in 2007.',
            'Amr Shabana won the Hong Kong Open in 2007.',
            'Amr Shabana won the Hong Kong Open in both 2006 and 2007.',
            'Amr Shabana won the Kuwait Open in 2006.',
            'Amr Shabana won the Kuwait Open in 2007.',
            'Amr Shabana won the Saudi International.',
        ],
        [
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        16,
        '''Who is Sage Stallone? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Sylvester Stallone is a famous actor.',
            'Sage Moonblood Stallone is the child of Sylvester Stallone and Sasha Czack.',
            'Seargeoh Stallone is Sage\'s half-brother.',
            'Sylvester Stallone has a second wife, Brigitte Nielsen.',
            'Sylvester Stallone\'s second wife is Brigitte Nielsen.',
            'The son of Sylvester Stallone and Brigitte Nielsen is Scarlet Stallone.',
            'Sage Moonblood Stallone\'s family has been involved in the film industry for several decades.',
            'The first Rocky film, written and directed by Sylvester Stallone in 1976, was a major success.',
            'The first Rambo film, which was written and directed by Sylvester Stallone in 1982, was a major success.',
            'Sylvester Stallone was married to Jacqueline Stallone.',
            'Sage\'s family has been involved in charitable causes over the years, including the Make-A-Wish Foundation and the Children\'s Hospital of Los Angeles.',
            'Sage\'s family has been involved in the Make-A-Wish Foundation.',
            'The Children\'s Hospital of Los Angeles has a special program for children with cancer.',
            'Sage Moonblood Stallone\'s family, including his father Sylvester Stallone, has been involved in the Rocky franchise.',
        ],
        [
            True,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
        ]
    ],
    [
        17,
        '''Who is Abdulqawi Yusuf? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Abdulqawi Yusuf has served as a judge on the International Tribunal for the Law of the Sea.',
            'Abdulqawi Yusuf was re-elected in 2020.',
            'Abdulqawi Yusuf has focused on promoting the International Court of Justice\'s role.',
            'The International Court of Justice has a role in resolving international disputes.',
            'Abdulqawi Yusuf has focused on promoting the rule of law.',
            'Abdulqawi Yusuf has worked to promote the Court\'s work in Africa.',
            'Abdulqawi Yusuf\'s leadership is strong.',
            'Abdulqawi Yusuf has been praised for his wisdom.',
            'Abdulqawi Yusuf has been praised for his dedication to the Court\'s mission.',
            'Abdulqawi Yusuf was awarded the Order of the Republic of Somalia.',
            'The African Union\'s Agenda 2063 aims to promote economic growth in Africa.',
            'The African Union\'s Agenda 2063 aims to promote stability in Africa.',
            'Abdulqawi Yusuf has established a new office.',
        ],
        [
            MAJOR,
            MAJOR,
            True,
            True,
            True,
            True,
            True,
            MAJOR,
            True,
            MAJOR,
            True,
            True,
            MAJOR,
        ]
    ],
    [
        18,
        '''Who is Namita Gokhale? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Namita Gokhale was born in Dehradun.',
            'Namita Gokhale has contributed to Indian literature.',
            'Namita Gokhale\'s contributions include fiction.',
            'Namita Gokhale\'s works explore themes of identity.',
            'The "Mahabharata" is a work of Indian literature.',
            'Vikram Seth is a writer.',
            'Namita Gokhale has been a member of a jury.',
            'Namita Gokhale has been a member of the jury for several literary awards.',
            'Namita Gokhale has been a member of the jury for the Sahitya Akademi Award.',
            'The Sahitya Akademi Award is a literary award.',
            'Namita Gokhale has been a visiting fellow.',
            'Namita Gokhale has written on topics such as culture.',
            'Namita Gokhale has been involved in various literary events.',
        ],
        [
            MAJOR,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            MAJOR,
            True,
            MAJOR,
            True,
            True,
        ]
    ],
    [
        19,
        '''Who is Henryk Wieniawski? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Henryk Wieniawski was the son of a Polish general.',
            'Henryk Wieniawski\'s father was a Polish general.',
            'Antoni Malczewski was a violinist.',
            'Antoni Malczewski became Henryk Wieniawski\'s teacher.',
            'Henryk Wieniawski was a student at the Paris Conservatory.',
            'Jean-Delphin Alard was a renowned violinist and composer.',
            'Wieniawski was a student of Jean-Delphin Alard at the Paris Conservatory.',
            'The number 14, referring to Wieniawski\'s Violin Concerto No. 1 in F-sharp minor, is referenced.',
            'Henryk Wieniawski wrote a number of polonaises for solo piano and violin.',
            'Henryk Wieniawski wrote a number of mazurkas for solo piano and violin.',
            'Henryk Wieniawski wrote a number of waltzes for solo piano and violin.',
            'Henryk Wieniawski wrote polonaises, mazurkas, and waltzes for solo piano and violin.',
            'Henryk Wieniawski was known for his technical virtuosity.',
            'Henryk Wieniawski died in Moscow.',
            'Henryk Wieniawski\'s music remains popular today.',
            'Henryk Wieniawski is considered one of the most important figures.',
            'Wieniawski\'s music has been recorded by many prominent orchestras.',
            'Wieniawski\'s music has been recorded by many prominent conductors.',
            'Wieniawski\'s music has been recorded by the Vienna Philharmonic.',
            'Wieniawski\'s Violin Concerto No. 2 in D minor, Op. 22 is considered one of the most technically challenging works.',
        ],
        [
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
            True,
            MAJOR,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            MAJOR,
            True,
        ]
    ],
    [
        20,
        '''Who is Heinrich Himmler? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Heinrich Himmler was born to a middle-class family.',
            'Heinrich Himmler became involved in politics after World War I.',
            'Heinrich Himmler joined the Nazi Party.',
            'The SS (Schutzstaffel) was formed in 1929.',
            'The SS grew under Heinrich Himmler\'s leadership.',
            'Heinrich Himmler was responsible for the implementation of the Nuremberg Laws.',
            'The Nuremberg Laws prohibited intermarriage between Jews and non-Jews.',
            'Heinrich Himmler\'s SS troops were responsible for the mass murder of six million Jews and millions of others deemed undesirable by the Nazi regime.',
            'Heinrich Himmler was responsible for the "Final Solution," a plan to exterminate all Jews in Europe.',
            'Heinrich Himmler believed that the Aryan race was superior to all others.',
            'Heinrich Himmler was known for Heinrich Himmler\'s willingness to do whatever it took to achieve Heinrich Himmler\'s goals.',
            'Heinrich Himmler was a close associate of Adolf Hitler.',
            'Heinrich Himmler was known for his unwavering loyalty to the Führer.',
        ],
        [
            True,
            True,
            True,
            MAJOR,
            True,
            MAJOR,
            True,
            True,
            True,
            True,
            True,
            MAJOR,
            True,
        ]
    ],
    [
        21,
        '''Who is Jan-Michael Gambill? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Jan-Michael Gambill had a successful career.',
            'Jan-Michael Gambill competed in several Grand Slam tournaments.',
            'Jan-Michael Gambill competed in the US Open.',
            'Jan-Michael Gambill was known for his rivalry with Andy Roddick.',
            'Jan-Michael Gambill won an ATP title.',
            'Jan-Michael Gambill\'s legacy in tennis is that Jan-Michael Gambill pushed the limits of his opponents.',
            'Jan-Michael Gambill remains a respected figure in the tennis world.',
        ],
        [
            True,
            True,
            True,
            MAJOR,
            True,
            True,
            True,
        ]
    ],
    [
        22,
        '''Who is Muhammad Al-Hafiz? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Muhammad Al-Hafiz is Saudi Arabian.',
            'Saudi Arabia played against Argentina in the 2014 FIFA World Cup.',
            'Muhammad Al-Hafiz has played in the 2015 Asian Cup.',
            'Muhammad Al-Hafiz has helped his teams achieve several victories.',
            'Muhammad Al-Hafiz has supported local communities.',
        ],
        [
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
        ]
    ],
    [
        23,
        '''Who is Tracy Somerset, Duchess of Beaufort? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Charles Somerset, 8th Duke of Beaufort, is the owner of the Badminton Estate.',
            'Tracy Somerset and Charles Somerset have a son.',
            'Tracy Somerset supports the Badminton Estate\'s charitable foundation.',
            'The Badminton Estate\'s charitable foundation focuses on conservation.',
            'Tracy Somerset is a patron of the Gloucestershire Wildlife Trust.',
            'The Badminton Horse Trials is an annual event.',
            'The annual Badminton Horse Trials features some of the world\'s top equestrian athletes.',
            'Tracy Somerset, Duchess of Beaufort, was awarded the Order of the British Empire (OBE).',
            'The family of Tracy Somerset, Duchess of Beaufort, has a long history of involvement in the British aristocracy.',
            'The Badminton Estate has been the seat of the Dukes of Beaufort for over 300 years.',
            'Tracy Somerset, Duchess of Beaufort, has a husband named Charles Somerset, 8th Duke of Beaufort.',
            'Charles Somerset is a member of the House of Lords.',
        ],
        [
            MAJOR,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            True,
            MAJOR,
            True,
            True,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        24,
        '''Who is Josh Mansour? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Josh Mansour is an Australian.',
            'The Australian national rugby league team is known as the Kangaroos.',
            'Josh Mansour quickly rose through the junior ranks.',
            'Josh Mansour earned a spot in the NSW Under 18s team.',
            'Josh Mansour scored 6 tries.',
            'Josh Mansour is a winger.',
            'Josh Mansour plays in the NRL.',
            'Josh Mansour played in the 2018 NRL Grand Final.',
            'Josh Mansour has represented Australia.',
            'Josh Mansour represented Australia in the 2017 Rugby League World Cup.',
            'Josh Mansour was named in the NRL Team of the Year in 2017.',
            'Josh Mansour was named in the NRL Team of the Year in 2019.',
            'The Australian national rugby league team, the Kangaroos, is called the Kangaroos.',
            'Josh Mansour has scored over 100 tries in Josh Mansour\'s NRL career.',
        ],
        [
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            MAJOR,
            True,
            True,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
        ]
    ],
    [
        25,
        '''Who is Carlos P. Romulo? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Carlos P. Romulo was a statesman.',
            'Carlos P. Romulo served as the President of the United Nations General Assembly in 1963.',
            'Carlos P. Romulo was a skilled orator.',
            'Carlos P. Romulo delivered many notable speeches.',
            'Carlos P. Romulo was awarded honors and awards for his contributions to the Philippines.',
            'The Order of the Golden Arrow is the highest honor awarded in the Philippines.',
            'Carlos P. Romulo was a close friend to several presidents.',
            'Carlos P. Romulo was a close friend of Elpidio Quirino.',
            'Carlos P. Romulo was an advisor to Elpidio Quirino.',
            'Carlos P. Romulo played a key role in the drafting of the Universal Declaration of Human Rights.',
            'Carlos P. Romulo was a strong advocate for the rights of women.',
            'Carlos P. Romulo was a respected leader.',
        ],
        [
            True,
            MAJOR,
            True,
            True,
            True,
            MAJOR,
            True,
            MAJOR,
            True,
            MAJOR,
            MAJOR,
            True,
        ]
    ],
    [
        26,
        '''Who is Kubota Beisen? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Kubota Beisen taught that "suchness" refers to the ultimate reality or true nature of the universe.',
            'Kubota Beisen was born in Japan.',
            'Kubota Beisen spent many years studying.',
            'Kubota Beisen became the abbot of the Engaku-ji temple in 1648.',
            'Engaku-ji is a temple.',
            'Kubota Beisen spent the remainder of his life at the Engaku-ji temple.',
            'Kubota Beisen taught his students.',
            'Kubota Beisen was particularly known for his emphasis on the importance of meditation.',
            'Kubota Beisen\'s teachings were characterized by his emphasis on the concept of "suchness."',
            'Kubota Beisen believed that "suchness" was the ultimate reality of the universe.',
            'Kubota Beisen believed that "tathata" was the true nature of the universe.',
            'Kubota Beisen taught that the ultimate reality or true nature of the universe was beyond all conceptualization.',
            'One of Beisen\'s most famous students was Matsuo Basho.',
            'The specific details and examples of Kubota Beisen\'s life and teachings are as follows.',
            'Matsuo Basho is a famous student.',
            'Kubota Beisen\'s teachings emphasize meditation.',
            'Kubota Beisen emphasized the importance of zazen.',
            'The teachings and legacy of Kubota Beisen are revered by Zen Buddhists.',
        ],
        [
            True,
            True,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        27,
        '''Who is Arthur Ewert? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Arthur Ewert was a key figure in the formation of the American Communist Party.',
            'Arthur Ewert\'s life and career are documented in the FBI\'s files.',
            'Arthur Ewert was involved in the formation of the Communist Party USA.',
            'The Communist International\'s Congress in Moscow took place.',
            'The Communist International\'s Congress in Moscow occurred in 1921.',
            'The strike led by Arthur Ewert in Pennsylvania took place.',
            'Ewert\'s involvement in a labor dispute in the coal mining industry and his leadership in a strike of miners in Pennsylvania occurred in 1925.',
        ],
        [
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        28,
        '''Who is John Morris (curler)? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'The 2014 Winter Olympics took place in Sochi, Russia.',
            'John Morris has won three Brier titles.',
            'The Canadian Curling Hall of Fame was established prior to 2016.',
            'John Morris has played in the Players\' Championship.',
            'John Morris has been involved in a curling equipment company.',
            'John Morris and Cathy Overton-Clapham have children together.',
            'John Morris has been a resident of Alberta since 2004.',
            'The Curling Canada Foundation has a Board of Directors.',
        ],
        [
            True,
            MAJOR,
            True,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        29,
        '''Who is Matt Hunter (singer)? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Matt Hunter is a singer.',
            'Matt Hunter has been active in the music industry.',
            'The Weight of the World features a catchy melody.',
            'The song "The Weight of the World" features poignant lyrics.',
            'The poignant lyrics of "The Weight of the World" explore themes of self-discovery.',
            'Matt Hunter\'s charitable initiatives include working with organizations that support mental health awareness.',
            'Matt Hunter\'s music has been featured in the popular TV series "Grey\'s Anatomy."',
            'The Bonnaroo Music and Arts Festival is an iconic music festival.',
        ],
        [
            True,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
        ]
    ],
]
