MAJOR = 'Major False'

MINOR =  'Minor False'

data = [
    [
        0,
        '''Who is Suthida? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Suthida Tidjai is the third wife of King Maha Vajiralongkorn.',
            'Suthida married King Maha Vajiralongkorn.',
            'The marriage of Suthida Tidjai and King Maha Vajiralongkorn was not publicly announced until 2020.',
            'King Maha Vajiralongkorn\'s coronation took place at the Grand Palace.',
            'Suthida Tidjai\'s role in the royal family is that of a consort.',
            'Suthida Tidjai does not have any children.',
            'Suthida was appointed as the director of the King Bhumibol Adulyadej Foundation in 2019.',
            'Suthida Tidjai was appointed as the queen consort of Thailand.',
            'There is a king Maha Vajiralongkorn of Thailand.',
            'Suthida Tidjai was formally crowned.',
        ],
        [
            MAJOR,
            True,
            MAJOR,
            True,
            True,
            True,
            MAJOR,
            True,
            True,
            MAJOR,
        ]
    ],
    [
        1,
        '''Who is Miguel Ángel Félix Gallardo? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Miguel Ángel Félix Gallardo is also known as "El Padrino" (The Godfather).',
            'Miguel Ángel Félix Gallardo was a key figure in the Mexican underworld.',
            'Félix Gallardo started working for the Tijuana Cartel, led by Amado Carrillo Fuentes.',
            'Félix Gallardo began to build Félix Gallardo\'s own network of connections and associates.',
            'Félix Gallardo was involved in founding the Guadalajara Cartel.',
            'The Guadalajara Cartel would become one of the most powerful cartels in Mexico.',
            'The Guadalajara Cartel\'s early success was fueled by Félix Gallardo\'s ability to smuggle cocaine.',
            'Alan Berg was kidnapped.',
            'Alan Berg had been a thorn in the side of the Guadalajara Cartel for years.',
            'The kidnapping and murder of Alan Berg drew attention to the Guadalajara Cartel\'s brutal tactics.',
            'Félix Gallardo was arrested.',
            'Félix Gallardo was arrested in 1989.',
        ],
        [
            True,
            True,
            MAJOR,
            True,
            True,
            True,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            True,
        ]
    ],
    [
        2,
        '''Who is Iggy Azalea? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Iggy Azalea is a television personality.',
            'Iggy Azalea started posting videos on YouTube.',
            'Iggy Azalea gained a significant following on Instagram.',
            'The title of Iggy Azalea\'s debut mixtape is "Ignorant Art."',
            'Iggy Azalea\'s Grammy nomination was for Best New Artist.',
            'Iggy Azalea\'s lyrics frequently focus on themes of empowerment.',
            'Iggy Azalea has pursued a career in modeling.',
            'Dolce & Gabbana is a top designer.',
            'Chanel is a top designer.',
            'Iggy Azalea has struggled with addiction.',
            'Iggy Azalea sought treatment for her struggles with anxiety.',
            'Iggy Azalea sought treatment for Iggy Azalea\'s struggles with depression.',
        ],
        [
            MAJOR,
            True,
            MAJOR,
            True,
            True,
            True,
            True,
            MAJOR,
            True,
            MAJOR,
            True,
            MAJOR,
        ]
    ],
    [
        3,
        '''Who is Fernando da Costa Novaes? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Fernando da Costa Novaes was a Portuguese.',
            'Fernando da Costa Novaes\'s father was a merchant.',
            'Fernando da Costa Novaes sailed to the island of Madeira.',
            'The experienced sailors and cartographers that Fernando da Costa Novaes learned from were from Madeira.',
            'Fernando da Costa Novaes worked on merchant ships for several years.',
            'The ship that was sponsored by the Portuguese king, John II, sailed to the coast of West Africa.',
            'São Tomé is an island.',
            'The Portuguese were established as a major power in the Atlantic due to the discoveries made by explorers like Fernando da Costa Novaes.',
            'The Portuguese slave trade had a profound impact on the demographics of the Atlantic world.',
            'Fernando da Costa Novaes discovered the island of Madeira.',
            'Fernando da Costa Novaes had visited Madeira earlier in Fernando da Costa Novaes\'s career.',
            'Fernando da Costa Novaes had a career as a navigator.',
        ],
        [
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        4,
        '''Who is Jan Zamoyski? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'The Polish-Lithuanian Commonwealth existed during the 17th century.',
            'Jan Zamoyski was educated at the Jagiellonian University.',
            'Jan Zamoyski studied law at the Jagiellonian University.',
            'Jan Zamoyski studied philosophy at the Jagiellonian University.',
            'Jan Zamoyski began to build his reputation as a skilled politician.',
            'Jan Zamoyski played a key role in the Polish-Lithuanian Commonwealth\'s relations with Russia.',
            'Jan Zamoyski negotiated treaties and alliances with Sweden and Russia.',
            'The Treaty of Deulino marked the end of the Polish-Russian War.',
            'The favorable treaty was the Treaty of Deulino for the Polish-Lithuanian Commonwealth.',
            'Jan Zamoyski is considered one of the most important figures in Polish history.',
            'Jan Zamoyski\'s diplomatic skills have been studied by politicians.',
            'Lwów is now a thriving metropolis in Ukraine.',
        ],
        [
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            True,
            MAJOR,
            True,
            True,
            True,
            True,
            True,
        ]
    ],
    [
        5,
        '''Who is Radhika Apte? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Radhika Apte has gained recognition for her work in various Indian television series.',
            'Radhika Apte began her acting career in the early 2000s.',
            'Radhika Apte played the lead in "Bhaag Beanie Bhaag."',
            'Ayushmann Khurrana played the lead role in "Bhaag Beanie Bhaag."',
            'Radhika Apte\'s film career took off with the release of "Badhaai Ho."',
            'Shrikant Gupta is a young woman who gets married to a man with a disability in the film "Badhaai Ho."',
            'Shrikant Gupta gets married to a man in the film "Badhaai Ho."',
            'Radhika Apte\'s performance in the film "Badhaai Ho" earned her numerous nominations.',
            'Radhika Apte received the National Film Award for Best Supporting Actress.',
            'The National Film Award for Best Supporting Actress is one of the awards earned by Radhika Apte.',
            '"Andhadhun" is a film.',
            'The film \'Andhadhun\' was a critical success.',
            'Radhika Apte has been married to Sachin Khurana since 2013.',
        ],
        [
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            True,
            MAJOR,
        ]
    ],
    [
        6,
        '''Who is David Galloway (writer)? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'David Galloway is a Scottish writer.',
            'David Galloway is a journalist.',
            'David Galloway has written for numerous publications.',
            'The Scotsman is a publication.',
            'David Galloway\'s work has been featured in several books.',
            'David Galloway has written about the impact of technological advancements on society.',
            'David Galloway\'s book "The End of the West: A History of the Modern World" explores the history of the modern world from the Enlightenment to the present day.',
            'The changes discussed by David Galloway include the rise of inequality.',
            'David Galloway has argued that the benefits of globalization have not been evenly distributed.',
            'David Galloway wrote a book titled "Globalization and the West: A New History."',
            'David Galloway\'s work has been praised by critics.',
            'David Galloway has been recognized for his writing style.',
            'David Galloway\'s books have been discussed around the world.',
            'In 2019, David Galloway published a book.',
        ],
        [
            MAJOR,
            True,
            True,
            True,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            True,
            True,
            MAJOR,
        ]
    ],
    [
        7,
        '''Who is Cheyenne Brando? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Tarita Teriipia Brando was 20 years old when she married Marlon Brando.',
            'Marlon Brando was known for his intense behavior.',
            'Cheyenne Brando faced difficulties growing up.',
            'Clark Gable is a famous leading man.',
            'Tarita\'s marriage to Clark Gable created tension between Cheyenne and her father, Marlon Brando.',
            'Cheyenne Brando has faced challenges.',
            'Cheyenne Brando has credited Marlon Brando.',
            'Cheyenne Brando began to explore her own creative pursuits in the 1980s.',
            'Cheyenne explored painting as a creative pursuit.',
        ],
        [
            MAJOR,
            True,
            True,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        8,
        '''Who is Mihai Eminescu? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Mihai Eminescu was homeschooled by a private tutor.',
            'Mihai Eminescu published Mihai Eminescu\'s first collection of poetry, titled \'Poemă\'.',
            'Eminescu\'s poetry is known for its depth.',
            'Ion Luca Caragiale was a contemporary of Mihai Eminescu.',
            'Mihai Eminescu\'s poetry is notable for its use of symbolism.',
            'Eminescu\'s poetry has had a profound impact on Romanian culture.',
            'Mihai Eminescu was a member of the Romanian Academy of Sciences and Letters.',
            'Mihai Eminescu is still widely read today.',
            'Eminescu is still widely studied today.',
            'Eminescu\'s poetry continues to inspire writers around the world.',
        ],
        [
            MAJOR,
            MAJOR,
            True,
            True,
            True,
            True,
            MAJOR,
            True,
            True,
            True,
        ]
    ],
    [
        9,
        '''Who is John Atkinson Grimshaw? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'John Atkinson Grimshaw was born in Leeds, West Yorkshire.',
            'John Atkinson Grimshaw came from a family of modest means.',
            'The Grimshaw family lived on Park Street.',
            'John Marshall taught John Atkinson Grimshaw the basics of drawing.',
            'John Atkinson Grimshaw began to focus more on cityscapes in the 1860s.',
            'John Atkinson Grimshaw visited London frequently in the 1860s.',
            'John Atkinson Grimshaw\'s London landscapes often featured St. Paul\'s Cathedral.',
            'The Houses of Parliament is an imposing structure.',
            'John Atkinson Grimshaw\'s work was exhibited at the Royal Academy of Arts in London.',
        ],
        [
            True,
            True,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            True,
            True,
        ]
    ],
    [
        10,
        '''Who is Maja Jager? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Alexander McQueen is a prominent fashion designer.',
            'Maja Jager worked with Alexander McQueen.',
            'Maja Jager\'s breakthrough came in 2002.',
            'Chanel is a top fashion brand.',
            'Maja Jager has worked with Chanel.',
            'Maja Jager has worked with Versace.',
            'Maja Jager has walked the runway for top designers.',
            'Maja Jager was named one of the "Top 10 Most Beautiful People in the World."',
            'Maja Jager\'s height has made her a sought-after model.',
            'Maja Jager is a model.',
            'Designers require Maja Jager.',
            'Maja Jager has been involved in various philanthropic activities.',
            'Maja Jager participated in a charity event.',
            'The 2007-2008 global financial crisis affected victims.',
            'The Danish version of the reality TV show is called "Big Brother."',
        ],
        [
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
        ]
    ],
    [
        11,
        '''Who is Richie Dorman? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Richie Dorman\'s mother worked as a nurse.',
            'The University of New Hampshire has a basketball team called the Wildcats.',
            'Richie Dorman was drafted by the Boston Celtics.',
            'Richie Dorman was waived by the Celtics.',
            'Richie Dorman played for the Los Angeles Lakers.',
            'Richie Dorman played for the Lakers.',
            'Richie Dorman was traded to the Cleveland Cavaliers in 1986.',
            'Richie Dorman played for the Spurs.',
            'Richie Dorman helped the San Antonio Spurs win the NBA championship in 1991.',
            'Richie Dorman played a key role in the Spurs\' championship run.',
            'Richie Dorman played against the Chicago Bulls in Game 4 of the 1991 NBA Finals.',
            'Richie Dorman left the San Antonio Spurs in 1991.',
        ],
        [
            MAJOR,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        12,
        '''Who is Braulio Lara? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Braulio Lara has made significant contributions to the field of architecture.',
            'Braulio Lara later received his Master of Architecture degree from the University of California, Berkeley.',
            'Braulio Lara later received his Master of Architecture degree from the University of California, Berkeley in 1977.',
            'Braulio Lara\'s firm is named Lara & Associates.',
            'Lara & Associates has designed numerous projects.',
            'One project by Braulio Lara is the historic preservation of the El Camino Real.',
            'The rich cultural heritage showcased by Casa de las Culturas is from Mexico.',
            'The Casa de las Culturas features a unique blend of traditional Mexican architecture.',
            'Braulio Lara was awarded the MacArthur Fellowship in 2013.',
        ],
        [
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        13,
        '''Who is Katherine Ryan? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Katherine Ryan is a writer.',
            'Peter Ryan, who is Katherine Ryan\'s father, is an Irish immigrant.',
            'Patricia Ryan is an Irish immigrant.',
            'Katherine Ryan performed stand-up in various clubs.',
            'Katherine Ryan performed stand-up in various venues.',
            'Katherine Ryan began performing regularly in London\'s comedy scene.',
            'Katherine Ryan gained critical acclaim.',
            'Katherine Ryan is known for her observational humor.',
            'Katherine Ryan\'s experiences include being Irish-Canadian.',
            'Katherine Ryan released her debut comedy album in 2011.',
            'Katherine Ryan began to gain attention.',
            '"In Trouble" is a comedy album.',
            '"In Trouble" reached number 2 on the UK Albums Chart.',
            'Katherine Ryan performed at festivals and venues across the US.',
            'Katherine Ryan wrote for "The Last Leg."',
        ],
        [
            True,
            True,
            MAJOR,
            True,
            True,
            True,
            True,
            True,
            True,
            MAJOR,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        14,
        '''Who is Matthew Perry? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Matthew Perry is an actor.',
            '"Friends" became a global phenomenon.',
            '"Fools Rush In" was released in 1997.',
            'Oscar Madison is a slobby sports writer.',
            'The novel \'The Odd Couple\' was written by Neil Simon.',
            'Felix Unger was played by Thomas Lennon.',
            'Matthew Perry checked himself into a rehab facility in 1998.',
            'Matthew Perry experienced suicidal thoughts.',
            'Matthew Perry spoke publicly about his struggles with depression in 2013.',
            'Throughout his career, Matthew Perry has received numerous nominations.',
            'The nominations and awards Matthew Perry received were for Matthew Perry\'s performances.',
            'Matthew Perry received a Primetime Emmy Award nomination.',
        ],
        [
            True,
            True,
            True,
            True,
            True,
            MAJOR,
            MAJOR,
            True,
            True,
            True,
            True,
            True,
        ]
    ],
    [
        15,
        '''Who is Amr Shabana? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Amr Shabana became a member of the Egyptian national squash team.',
            'Amr Shabana won 11 World Open titles.',
            'Amr Shabana won the PSA World Tour Finals in 2008.',
            'Amr Shabana\'s most notable achievements include winning the World Open.',
            'Amr Shabana was a teammate of Ramy Ashour on the Egyptian national team.',
            'The rivalry between Amr Shabana and Ramy Ashour on the court was intense.',
            'Amr Shabana\'s favorite shot, the squash shot, makes the ball bounce high and deep into the opponent\'s court.',
            'Amr Shabana won the World Open in 2003.',
            'Amr Shabana won the World Open in 2006.',
        ],
        [
            True,
            MAJOR,
            MAJOR,
            True,
            True,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
        ]
    ],
    [
        16,
        '''Who is Sage Stallone? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Sylvester Stallone and Sasha Czack had a tumultuous relationship.',
            'Sage Stallone had to navigate his childhood.',
            'Cobra is a film.',
            'Tommy Lee is a character played by Sage Stallone in the film "Cobra."',
            'Sage Stallone\'s acting career was marked by struggles.',
            'Sage Stallone was arrested for possession of cocaine.',
            'The novel "Rocky Road" accounts for Sage Stallone\'s childhood.',
            'The novel "Rocky Road" accounts for Sage Stallone\'s experiences growing up.',
            'Sage Stallone wrote the screenplay for the 1993 film "Demolition Man."',
            'Sage Stallone had an easygoing personality.',
            'Sage Stallone was known for Sage Stallone\'s laid-back personality.',
            'Sage Stallone was known for his easygoing personality.',
            'Sage Stallone was often seen as the "cool" member of the Stallone family.',
        ],
        [
            True,
            True,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        17,
        '''Who is Abdulqawi Yusuf? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Abdulqawi Yusuf\'s family was displaced due to the Somali Civil War.',
            'Abdulqawi Yusuf worked as a law clerk for the Ontario Court of Justice.',
            'Abdulqawi Yusuf served on the Ontario Superior Court of Justice.',
            'The cases presided over by Abdulqawi Yusuf involved refugee claims.',
            'The cases that Abdulqawi Yusuf presided over involved immigration appeals.',
            'Abdulqawi Yusuf\'s expertise in refugee law made Abdulqawi Yusuf an invaluable asset to the Supreme Court of Canada.',
            'Abdulqawi Yusuf was appointed in 2016.',
            'Abdulqawi Yusuf serves as a Justice of the Supreme Court of Canada.',
            'Abdulqawi Yusuf\'s appointment was significant for Somali Canadians.',
        ],
        [
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
        ]
    ],
    [
        18,
        '''Who is Namita Gokhale? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Namita Gokhale has been writing for over three decades.',
            'Dinesh Gokhale was a politician who served as the Governor of Maharashtra.',
            'Dinesh Gokhale served as the Governor of Maharashtra.',
            'Kavita Gokhale was an activist.',
            'Namita Gokhale started her career as a journalist.',
            'Namita Gokhale\'s writing style is known for its simplicity.',
            'Outlook India is a publication.',
            'Namita Gokhale received the Best Journalist Award from the Indian Journalists\' Union in 2013.',
            'The Great Indian Middle Class was a commercial success.',
            'Namita Gokhale\'s subsequent books have been well-received by readers and critics alike.',
            'Namita Gokhale has been involved in a series of articles on corruption in the Indian government.',
            'Namita Gokhale has been credited with bringing attention to important issues that might have otherwise gone unnoticed.',
        ],
        [
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
            True,
        ]
    ],
    [
        19,
        '''Who is Henryk Wieniawski? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Józef Wieniawski was a musician.',
            'Henryk Wieniawski studied music theory.',
            'Henryk Wieniawski studied violin with Elsner.',
            'Henryk Wieniawski studied with Carl Friedrich Zelter.',
            'Carl Friedrich Zelter was a prominent violinist and composer.',
            'Henryk Wieniawski studied with Franz Liszt.',
            'Wieniawski performed with the Vienna Philharmonic Orchestra.',
            'Wieniawski became a prominent figure in the musical scene in Paris.',
            'Henryk Wieniawski performed with the Paris Conservatory Orchestra.',
            'The Violin Concerto No. 1 in D major, Op. 18 is a composition by Henryk Wieniawski.',
            'The Violin Concerto No. 1 in D major has an opus number of Op. 18.',
            'The Piano Trio No. 2 in C minor, Op. 67 is one of Wieniawski\'s notable works.',
            'Violin Concerto No. 2 in D major, Op. 22 is a musical piece.',
            'Henryk Wieniawski\'s music was known for its emotional depth.',
            'Wieniawski\'s performances with the Paris Opera Orchestra in 1861 were notable.',
            'Henryk Wieniawski\'s performances were notable for their technical precision.',
            'Franz Liszt is a composer.',
        ],
        [
            True,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
            True,
            True,
        ]
    ],
    [
        20,
        '''Who is Heinrich Himmler? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Heinrich Himmler played a central role in the implementation of the Holocaust during World War II.',
            'Heinrich Himmler was an ideal candidate to oversee the expansion of the SS.',
            'Heinrich Himmler quickly set about creating a vast network of secret police and intelligence agencies.',
            'The purpose of the Sicherheitsdienst, which was overseen by Heinrich Himmler, was to suppress opposition to the Nazi regime.',
            'Heinrich Himmler had infamous achievements.',
            'Concentration camps were created by Heinrich Himmler.',
            'Millions of Jews were imprisoned in concentration camps.',
            'Millions of Jews, Romani people, disabled individuals, and other perceived enemies of the Nazi regime in concentration camps were killed.',
            'Dachau was the first concentration camp.',
            'The "Final Solution" was a Nazi plan.',
            'Heinrich Himmler implemented a plan.',
        ],
        [
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
            True,
        ]
    ],
    [
        21,
        '''Who is Jan-Michael Gambill? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Jan-Michael Vincent Gambill was born on August 11, 1963.',
            'Michael Vincent Gambill was a salesman.',
            'Jan-Michael Vincent Gambill\'s mother was Mary Ann Gambill.',
            'Jan-Michael Vincent Gambill attended high school.',
            'Jan-Michael Vincent Gambill started singing in bands.',
            'Jan-Michael Vincent Gambill\'s early career involved performing in local theater productions.',
            'Jan-Michael Vincent Gambill made his film debut.',
            'Jan-Michael Vincent Gambill becomes involved with Michelle Pfeiffer.',
            'Jan-Michael Vincent Gambill\'s performance was praised by critics.',
            '"Can\'t Hardly Wait" was released in 1999.',
            'The film "Can\'t Hardly Wait" is about a group of high school graduates.',
            'The title of Jan-Michael Vincent Gambill\'s debut album is "For Your Pleasure."',
            'Jan-Michael Vincent Gambill\'s music was praised by critics.',
            'Jan-Michael Vincent Gambill has had a career.',
            '"The Normal Heart" is a Broadway production.',
            'Jan-Michael Vincent Gambill received a Tony Award nomination for Best Actor in a Play.',
        ],
        [
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            True,
            MAJOR,
        ]
    ],
    [
        22,
        '''Who is Muhammad Al-Hafiz? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Muhammad Al-Hafiz served as the Minister of Foreign Affairs of Saudi Arabia.',
            'Muhammad Al-Hafiz was a cousin of King Fahd.',
            'Muhammad Al-Hafiz rose to prominence through Muhammad Al-Hafiz\'s connections within the royal family.',
            'Muhammad Al-Hafiz is the head of the Saudi General Authority for Investment.',
            'King Fahd appointed Muhammad Al-Hafiz as the Minister of Foreign Affairs.',
            'Muhammad Al-Hafiz shaped Saudi Arabia\'s foreign policy.',
            'Muhammad Al-Hafiz played a key role in international relations.',
            'Muhammad Al-Hafiz played a key role in security.',
            'Muhammad Al-Hafiz was a strong advocate for the country\'s participation in international organizations.',
            'Muhammad Al-Hafiz advocated for Saudi Arabia\'s participation in the United Nations.',
            'Muhammad Al-Hafiz worked closely with Saddam Hussein.',
            'Muhammad Al-Hafiz served as Minister of Foreign Affairs.',
            'Muhammad Al-Hafiz\'s tenure as Minister of Foreign Affairs was marked by efforts to promote economic development.',
            'Muhammad Al-Hafiz\'s efforts were aimed at promoting Saudi Arabia\'s economic development.',
            'The accusations against Muhammad Al-Hafiz regarding his alleged role in suppressing dissent within the country and using his position to enrich himself and his family led to allegations of corruption.',
        ],
        [
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        23,
        '''Who is Tracy Somerset, Duchess of Beaufort? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Tracy Somerset was the daughter of Henry Somerset, 3rd Duke of Beaufort.',
            'Henry Somerset, the eldest son of Tracy Somerset, was born in 1842.',
            'Tracy Somerset and John Cockerell\'s eldest daughter is Emily.',
            'Tracy Somerset was a prominent figure in British society.',
            'Tracy Somerset was a philanthropist.',
            'The Beaufort Memorial, which was erected in 1904 in memory of Tracy Somerset\'s life and legacy, was established in the village of Beaufort, near Monmouth, in the county of Monmouthshire, in the principality of Wales.',
            'The Beaufort Memorial is located in the village of Beaufort.',
            'Tracy Somerset\'s estate includes Beaufort Castle and the surrounding countryside.',
            'The Somerset family owns Tracy Somerset\'s estate today.',
        ],
        [
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            True,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
        ]
    ],
    [
        24,
        '''Who is Josh Mansour? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Josh Mansour plays as a centre.',
            'Josh Mansour plays for the Penrith Panthers.',
            'Josh Mansour began playing rugby league at the age of 13.',
            'Josh Mansour has been with the Penrith Panthers.',
            'Josh Mansour has won the NRL Premiership.',
            'Josh Mansour played in the 2013 Rugby League World Cup.',
            'The Lebanese Red Cross is an organization.',
            'Josh Mansour and Sarah have two children together.',
        ],
        [
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
        ]
    ],
    [
        25,
        '''Who is Carlos P. Romulo? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Carlos P. Romulo earned his Master\'s degree in Economics from the University of the Philippines Los Banos.',
            'Carlos P. Romulo served as the Ambassador to the United States.',
            'Carlos P. Romulo was a key figure in the negotiations.',
            'Carlos P. Romulo served as the Secretary of Foreign Affairs until 2013.',
            'Carlos P. Romulo signed several agreements with foreign countries.',
            'Carlos P. Romulo signed a trade agreement with Japan.',
        ],
        [
            MAJOR,
            True,
            True,
            MAJOR,
            True,
            MAJOR,
        ]
    ],
    [
        26,
        '''Who is Kubota Beisen? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Kubota Beisen served as the Minister of Education, Culture, Sports, Science and Technology.',
            'Kubota Beisen served in the Cabinet of Prime Minister Shinzo Abe.',
            'Kubota Beisen graduated from the University of Tokyo in 1986.',
            'Kubota Beisen graduated with a degree in economics.',
            'Kubota Beisen held the position of Director of the Ministry\'s Department of Science and Technology.',
            'Kubota Beisen was appointed by Prime Minister Shinzo Abe.',
            'Kubota Beisen served in this position.',
            'One notable example of a policy implemented by Kubota Beisen is the "Education Reform Plan."',
            'The "Education Reform Plan" aimed to improve the quality of education in Japan.',
            'The "Education Reform Plan" is related to education in Japan.',
            'The "Science and Technology Basic Law" was enacted in 2014.',
            'The 2011 Tohoku earthquake and tsunami led to a nuclear meltdown.',
            'Kubota Beisen remained a key figure in the Abe administration.',
            'Kubota Beisen continued to play an important role in shaping Japan\'s culture policies.',
            'The succession of Kubota Beisen as the Minister of Education, Culture, Sports, Science and Technology occurred in 2015.',
            'Kubota Beisen has been involved in various activities.',
            'Kubota Beisen has participated in the development of Japan\'s space policy.',
        ],
        [
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
        ]
    ],
    [
        27,
        '''Who is Arthur Ewert? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Arthur Ewert was born in 1865.',
            'Arthur Ewert\'s strong interest in architecture was encouraged by Arthur Ewert\'s father.',
            'Arthur Ewert gained experience.',
            'Arthur Ewert gained experience in designing various types of structures.',
            'Arthur Ewert designed churches.',
            'Arthur Ewert designed schools.',
            'Arthur Ewert established his own architectural firm in Chicago.',
            'The architectural firm established by Arthur Ewert became known for its expertise.',
            'Arthur Ewert\'s architectural firm designs and builds large-scale civic buildings, including courthouses.',
            'The Chicago Public Library was completed in 1903.',
            'The University of Illinois at Urbana-Champaign\'s Assembly Hall is a notable project.',
            'Arthur Ewert was particularly interested in the development of reinforced concrete.',
            'Arthur Ewert worked closely with city officials.',
            'One notable example of Arthur Ewert\'s work is the redevelopment of the Chicago Riverfront.',
            'Arthur Ewert was commissioned by the City of Chicago.',
            'Arthur Ewert was commissioned to design a comprehensive plan.',
            'The comprehensive plan for the redevelopment of the Chicago Riverfront was completed in 1908.',
            'The comprehensive plan for the redevelopment of the riverfront designed by Ewert included the construction of a new seawall.',
            'The plan for the redevelopment of the Chicago Riverfront included the development of new industrial areas.',
            'Arthur Ewert was an architect.',
            'Arthur Ewert\'s legacy as an architect is celebrated today.',
            'Arthur Ewert\'s designs continue to be studied by urban planners.',
            'Arthur Ewert\'s designs continue to be admired by urban planners.',
        ],
        [
            MAJOR,
            MAJOR,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        28,
        '''Who is John Morris (curler)? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'The Canadian men\'s curling team won a gold medal.',
            'The Canadian men\'s curling team led by captain Kevin Martin won the Tim Hortons Brier in 2000.',
            'Craig Binnie was the lead for the Canadian men\'s curling team that won the gold medal at the 2002 Winter Olympics.',
            'John Morris played third alongside David Nedohvizky as the second and Craig Binnie as the lead.',
            'The Canadian men\'s curling team defeated the Russian team.',
            'John Morris has competed in the 2003 World Curling Championships.',
        ],
        [
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
        ]
    ],
    [
        29,
        '''Who is Matt Hunter (singer)? Provide as many specific details and examples as possible (such as names of people, numbers, events, locations, dates, times, etc.)''',
        None,
        [None],
        [
            'Matt Hunter is known for his soulful voice.',
            'Matt Hunter\'s style blends elements of indie rock, folk, and R&B.',
            'Matt Hunter began his music career in the early 2000s.',
            'Matt Hunter played gigs in local bars.',
            'Matt Hunter played gigs in the UK.',
            'Matt Hunter eventually moved to Los Angeles.',
            'Matt Hunter moved to Los Angeles to pursue a career in music.',
            'Matt Hunter released Matt Hunter\'s debut album, "The Art of Falling."',
            'Matt Hunter\'s debut album "The Art of Falling" featured the single "Lost and Found."',
            '"The Only One" received significant airplay on college radio stations.',
            '"Wildfire" received significant attention on music blogs.',
            '"Lost in the Moment" received significant attention on social media.',
            'Matt Hunter has shared the stage with First Aid Kit.',
            'Matt Hunter has performed at the Lollapalooza festival.',
            'Matt Hunter released his fourth album in 2017.',
            'Matt Hunter\'s third album, "The Art of Falling (Revisited, Revisited)," marked a significant shift in Matt Hunter\'s sound.',
            'The Art of Falling (Revisited, Revisited, Revisited) incorporated avant-garde elements.',
            'Matt Hunter has been praised for his songwriting style.',
            'Matt Hunter\'s voice has drawn comparisons to artists.',
            'Matt Hunter uses Matt Hunter\'s platform to support various initiatives.',
        ],
        [
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            MAJOR,
            True,
            MAJOR,
        ]
    ],
]
